TRAIN:
  ENABLE: True
  DATASET: ssv1
  BATCH_SIZE: 32
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 1
  TRAIN_JITTER_SCALES: [114, 140]
  TRAIN_CROP_SIZE: 112
  TEST_CROP_SIZE: 128
  INPUT_CHANNEL_NUM: [3]
  INV_UNIFORM_SAMPLE: False
  RANDOM_FLIP: False
  REVERSE_INPUT_CHANNEL: True
COTERE:
  TYPE: CTSR
  C_MLP_R: 1.0
  T_MLP_R: 32.0
  S_CONV_SIZE: 3
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 30, 35, 40]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 174
  ARCH: r3d
  DEPTH: 18
  MODEL_NAME: CoTeReNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.0
TEST:
  ENABLE: True
  DATASET: ssv1
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
LOG_MODEL_INFO: True
